### ISSUE TITLE
Says "Project is currently open in Unity" even after Unity has been closed

### ISSUE THREAD

**Issue by hypevhs** [RinLovesYou/LinuxCreatorCompanion#1]
![Screenshot_20240211_184740](https://github.com/RinLovesYou/LinuxCreatorCompanion/assets/3746656/764be173-2d48-44fd-b6a3-6910236d7d39)

**Comment by RinLovesYou** [comment]
Haven't run into this yet, are you sure there isn't a unity process clinging to life in the background?

**Comment by hypevhs** [comment]
You're right, it seems that sometimes a Rosyln compiler process stays open, but only sometimes.

**Comment by RinLovesYou** [comment]
Alrighty, yeah sadly i don't think i can do anything about that
